---

- name: install packages
  apt:
       name: "{{ item }}"
       state: latest
       install_recommends: false
       update_cache: yes
       cache_valid_time: 300
  with_items: ufw

- name: reset firewall
  ufw:
       state: reset
  when: ufw_reset

- include: config.yml

- name: start firewall
  ufw:
       state: enabled
       logging: yes
